CREATE TABLE IF NOT EXISTS join_metadata_deduplicated (
    id SERIAL PRIMARY KEY,
    id_object TEXT,
    user_id TEXT,
    tags TEXT[],
    comment TEXT,
    timestamp TIMESTAMP,
    location TEXT,
    ingestion_time_ugc TIMESTAMP,
    source TEXT,
    creator TEXT,
    description TEXT,
    edm_rights TEXT,
    format TEXT,
    image_url TEXT[],
    isshownby TEXT[],
    language TEXT,
    provider TEXT,
    rights TEXT,
    subject TEXT[],
    timestamp_created_europeana TIMESTAMP,
    title TEXT,
    type TEXT,
    joined_at TIMESTAMP
);

-- Copia identica per staging
CREATE TABLE IF NOT EXISTS join_metadata_staging (
    id SERIAL PRIMARY KEY,
    id_object TEXT,
    user_id TEXT,
    tags TEXT[],
    comment TEXT,
    timestamp TIMESTAMP,
    location TEXT,
    ingestion_time_ugc TIMESTAMP,
    source TEXT,
    creator TEXT,
    description TEXT,
    edm_rights TEXT,
    format TEXT,
    image_url TEXT[],
    isshownby TEXT[],
    language TEXT,
    provider TEXT,
    rights TEXT,
    subject TEXT[],
    timestamp_created_europeana TIMESTAMP,
    title TEXT,
    type TEXT,
    joined_at TIMESTAMP
);