FROM python:3.10-slim

# Setta la working directory nel container
WORKDIR /app

# Copia tutti i file dalla directory locale
COPY . /app

# Installa le dipendenze da requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
